/* ═══════════════════════════════════════════════════════════
   Face data — the one thing the intro keeps from the original.

   public/face.bin is a packed ASCII "video" of the portrait reel
   (generated by scripts/generate-face-data.mjs): a cols×rows grid
   of luma per frame plus a sparse list of accent-coloured cells.
   ═══════════════════════════════════════════════════════════ */

export const FACE_URL = "/face.bin";
/** 12 levels, dark → light. Index 0 is empty. */
export const FACE_RAMP = " .·:;+=*x#%@";

export type FaceFrame = {
  luma: Uint8Array;
  accents: Array<{ i: number; r: number; g: number; b: number }>;
};

export type FaceData = {
  cols: number;
  rows: number;
  fps: number;
  frames: FaceFrame[];
};

export async function loadFaceData(): Promise<FaceData> {
  const res = await fetch(FACE_URL);
  if (!res.ok) throw new Error(`face.bin HTTP ${res.status}`);
  const buf = new Uint8Array(await res.arrayBuffer());
  if (buf[0] !== 0x46 || buf[1] !== 0x41 || buf[2] !== 0x43 || buf[3] !== 0x45) {
    throw new Error("bad magic");
  }
  const version = buf[4];
  if (version !== 1) throw new Error(`unsupported version ${version}`);
  const cols = buf[5];
  const rows = buf[6];
  const numFrames = buf[7] | (buf[8] << 8);
  const fps = buf[9] | (buf[10] << 8);

  let off = 16;
  const cellCount = cols * rows;
  const frames: FaceFrame[] = [];
  for (let f = 0; f < numFrames; f++) {
    const luma = buf.slice(off, off + cellCount);
    off += cellCount;
    const accCount = buf[off] | (buf[off + 1] << 8);
    off += 2;
    const accents = new Array(accCount);
    for (let k = 0; k < accCount; k++) {
      const i = buf[off] | (buf[off + 1] << 8);
      accents[k] = { i, r: buf[off + 2], g: buf[off + 3], b: buf[off + 4] };
      off += 5;
    }
    frames.push({ luma, accents });
  }
  return { cols, rows, fps, frames };
}

/** Where the face grid sits on screen: centred, cells ~1:1.7 so the portrait reads square. */
export function layoutFace(W: number, H: number, cols: number, rows: number) {
  const padW = Math.min(60, W * 0.05);
  const padH = Math.min(140, H * 0.16);
  const byW = (W - padW * 2) / cols;
  const byH = (H - padH * 2) / (rows * 1.7);
  const cellW = Math.max(3, Math.floor(Math.min(byW, byH)));
  const cellH = Math.round(cellW * 1.7);
  const fontPx = Math.max(4, Math.round(cellW * 1.8));
  const originX = Math.round((W - cellW * cols) / 2);
  const originY = Math.round((H - cellH * rows) / 2);
  return { cellW, cellH, fontPx, originX, originY };
}

/** Glyph for a luma value (or "" for empty). */
export function faceGlyph(luma: number): string {
  const ci = Math.round((luma / 255) * (FACE_RAMP.length - 1));
  return ci === 0 ? "" : FACE_RAMP[ci];
}

/** Display colour of a face cell: accent cells keep their (brightened) RGB, the rest are warm-white by luma. */
export function faceCellRgb(
  luma: number,
  accent: { r: number; g: number; b: number } | undefined,
): [number, number, number] {
  if (accent) {
    return [
      Math.min(255, Math.round(accent.r * 1.35 + 40)),
      Math.min(255, Math.round(accent.g * 1.35 + 40)),
      Math.min(255, Math.round(accent.b * 1.35 + 40)),
    ];
  }
  const bw = Math.min(255, Math.round(180 + (luma / 255) * 75));
  return [bw, bw, bw];
}
